#!/bin/sh
#this file goes in ~/.vnc
#this file needs to executable "chmod 755 startx"
xset -b # disable bell
xrdb $HOME/.Xresources
xmodmap ~/.Xmodmap
xsetroot -solid black
#setxkbmap -option ctrl:nocaps
xmodmap -e 'clear Lock'
xmodmap -e 'keycode 89 = Control_L'
st -f "mono:pixelsize=32" -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
exec dwm &
