#!/bin/sh
#this file goes in ~/.vnc
#this file needs to executable "chmod 755 xstartup"
xset -b # disable bell
xrdb $HOME/.Xresources
xmodmap ~/.Xmodmap
xsetroot -solid black
setxkbmap -option ctrl:nocaps
#xmodmap -e 'clear Lock'
#xmodmap -e 'keycode 89 = Control_L'
urxvt -fn "xft:mono:pixelsize=32" -rv +sb &
exec dwm &
